### ISSUE TITLE
Burst address for numeric ID 0 incorrect

### ISSUE THREAD

**Issue by llybin** [burst-apps-team/burst-wiki#48]
https://github.com/burst-apps-team/burst-wiki/blob/master/docs/en/internal-at-and-escrow-account.md

Currently in WIKI (text, pic, by explorer url): BURST-2222-2222-TMT9-J2222
Should be BURST-2222-2222-2222-22222

https://explore.burst.cryptoguru.org/account/0 - 2222-2222-2222-22222
https://explorer.burst.devtrue.net/address/0 - 2222-2222-2222-22222
https://explorer.burstcoin.network/?action=account&account=0 and WIKI - 2222-2222-TMT9-J2222

![image](https://user-images.githubusercontent.com/5445357/76536828-700a5080-64af-11ea-96eb-d5b861e28950.png)

**Comment by harryjph** [comment]
Good catch!

**Comment by holycow131415** [comment]
so https://explorer.burstcoin.network is incorrect?

**Comment by llybin** [comment]
Yes

**Comment by Zoh63392187** [comment]
Fixed
